### ISSUE TITLE
[FR] Ability to use Environment Variables in YML file

### ISSUE THREAD

**Issue by JohnLegrandRichards** [kamranahmedse/itomate#13]
Ability to use ENV variables in the YML configuration is very important to hide secrets or give developers a chance to create more generalized templates

root: !ENV ${MYPROJECT_ROOT_PATH}

**Comment by nilbuild** [comment]
This has been released in [`0.3.1`](https://github.com/kamranahmedse/itomate/releases/tag/0.3.1). Thanks @JohnLegrandRichards!
