### ISSUE TITLE
[FR] Select iTerm profile for a new window

### ISSUE THREAD

**Issue by jaklan** [kamranahmedse/itomate#15]
Currently using `itomate` with `-n` option to create a new window would use a default iTerm profile. It would be valuable to be able to select a custom profile, e.g. with different shell or window size.

**Comment by JohnLegrandRichards** [comment]
@jaklan I will work on this today or tomorrow.

**Comment by nilbuild** [comment]
This has been added in `0.3.6`. Thanks!
