### ISSUE TITLE
Feature request: configure the size of the iTerm window

### ISSUE THREAD

**Issue by alexandre-delaloy** [kamranahmedse/itomate#2]
Hi !

First of all, **thank you** ! I've been looking for this kind of automation tool for iTerm2 for *looong* time!

I was wondering, it might be possible to define the **size** of the window at launch.

2 parameters here:
-  **original / latest screen resolution** OR **full screen**  at launch
-  **"native full screen windows"** activated or not (Preferences> General> Window)

I don't know if this is something that can be simply configured.

**Comment by nilbuild** [comment]
Thank you for opening the issue. I looked at the [iTerm API docs](https://www.iterm2.com/python-api/window.html) and I couldn't find anything for resizing so I don't think it's possible with the API. 

They [allow setting profiles](https://www.iterm2.com/python-api/profile.html) though. I am not sure if we can save window sizing as a part of the profile and maybe [support switching profiles](https://www.iterm2.com/python-api/profile.html).
