### ISSUE TITLE
commands not executed within python3.8

### ISSUE THREAD

**Issue by informautico** [kamranahmedse/itomate#22]
I just upgraded the python version from 3.7 to 3.8.
Now the commands defined on the .yml aren't launched. Instead of that, they're printed without being executed.

It was working correctly with the 3.7  but not within the 3.8

**Comment by JohnLegrandRichards** [comment]
Python 3.8.0 can only be used with ITerm2 3.3.7beta3 or later. Can you let me know if you are using that version? If you upgrade and it fixes it let me know and I will change the readme.

**Comment by JohnLegrandRichards** [comment]
It was a bug in the code @informautico. Pull request is up. you should be fine with 3.8

**Comment by informautico** [comment]
Great. Txs

**Comment by nilbuild** [comment]
Thanks, @JohnLegrandRichards and @informautico.
@informautico v3.8 has been published, please let us know if you face any issues.

**Comment by informautico** [comment]
Confirmed. v3.8 solved the issue.
Good job.
