### ISSUE TITLE
[FR] Highlight selected pane, not the last one

### ISSUE THREAD

**Issue by jaklan** [kamranahmedse/itomate#3]
Hi, great idea with the lib! However, I have two notes (the second one in another issue).

The first one is the option to select which pane should be highlighted after creation. Now, when I have 3 panes: 1/1, 2/1, 2/2, the one always highlighted is 2/2. I'd like to be able to choose e.g. 1/1 as the default one.

**Comment by nilbuild** [comment]
This has been added in the latest release `0.3.0`. You can specify `focus` in [the configuration](https://github.com/kamranahmedse/itomate#configuration).
